### ISSUE TITLE
latest main branch breaks scripts/combine/setupCombineWmass.py

### ISSUE THREAD

**Issue by tyjyang** [WMass/WRemnants#91]
I synced with the main branch, but ran into the following errors when running `scripts/combine/setupCombineWmass.py`.

With `python scripts/combine/setupCombineWMass.py -i mw_with_mu_eta_pt.pkl.lz4 -o ../combine_files/smearing-weights`, I got:
```
INFO:wremnants.CardTool:Writing systematic luminosity for process Top
Traceback (most recent call last):
  File "/home/t/tyjyang/analysis/wmass/WRemnants/scripts/combine/setupCombineWMass.py", line 267, in <module>
    main(args)
  File "/home/t/tyjyang/analysis/wmass/WRemnants/scripts/combine/setupCombineWMass.py", line 262, in main
    cardTool.writeOutput()
  File "/home/t/tyjyang/analysis/wmass/WRemnants/wremnants/CardTool.py", line 382, in writeOutput
    self.writeForProcesses(syst, label="syst", processes=processes)
  File "/home/t/tyjyang/analysis/wmass/WRemnants/wremnants/CardTool.py", line 351, in writeForProcesses
    self.writeForProcess(hvar, process, syst)
  File "/home/t/tyjyang/analysis/wmass/WRemnants/wremnants/CardTool.py", line 322, in writeForProcess
    var_names, variations = self.systHists(h, syst)
  File "/home/t/tyjyang/analysis/wmass/WRemnants/wremnants/CardTool.py", line 274, in systHists
    raise ValueError(f"Failed to find axis names {str(axNames)} in hist for syst {syst}. " \
ValueError: Failed to find axis names ['downUpVar'] in hist for syst luminosity. Axes in hist are ('eta', 'pt', 'charge')
```
Commenting out the luminosity part, I still got:
```
INFO:wremnants.CardTool:Writing systematic effSystTnP for process Zmumu
Traceback (most recent call last):
  File "/home/t/tyjyang/analysis/wmass/WRemnants/scripts/combine/setupCombineWMass.py", line 269, in <module>
    main(args)
  File "/home/t/tyjyang/analysis/wmass/WRemnants/scripts/combine/setupCombineWMass.py", line 264, in main
    cardTool.writeOutput()
  File "/home/t/tyjyang/analysis/wmass/WRemnants/wremnants/CardTool.py", line 382, in writeOutput
    self.writeForProcesses(syst, label="syst", processes=processes)
  File "/home/t/tyjyang/analysis/wmass/WRemnants/wremnants/CardTool.py", line 351, in writeForProcesses
    self.writeForProcess(hvar, process, syst)
  File "/home/t/tyjyang/analysis/wmass/WRemnants/wremnants/CardTool.py", line 322, in writeForProcess
    var_names, variations = self.systHists(h, syst)
  File "/home/t/tyjyang/analysis/wmass/WRemnants/wremnants/CardTool.py", line 274, in systHists
    raise ValueError(f"Failed to find axis names {str(axNames)} in hist for syst {syst}. " \
ValueError: Failed to find axis names ['reco-tracking-idiptrig-iso', 'mirror'] in hist for syst effSystTnP. Axes in hist are ('eta', 'pt', 'charge', 'idiptrig-iso', 'mirror')
```
With the `--noEfficiencyUnc` flag enabled, this error shows up instead:
```
INFO:wremnants.CardTool:Writing systematic QCDscaleZ for process Ztautau
Traceback (most recent call last):
  File "/home/t/tyjyang/analysis/wmass/WRemnants/scripts/combine/setupCombineWMass.py", line 269, in <module>
    main(args)
  File "/home/t/tyjyang/analysis/wmass/WRemnants/scripts/combine/setupCombineWMass.py", line 264, in main
    cardTool.writeOutput()
  File "/home/t/tyjyang/analysis/wmass/WRemnants/wremnants/CardTool.py", line 379, in writeOutput
    self.datagroups.loadHistsForDatagroups(self.histName, systName, label="syst",
  File "/home/t/tyjyang/analysis/wmass/WRemnants/wremnants/datasets/datagroups.py", line 137, in loadHistsForDatagroups
    self.setHists(baseName, syst, procsToRead, label, nominalIfMissing, selectSignal, forceNonzero, preOpMap, preOpArgs)
  File "/home/t/tyjyang/analysis/wmass/WRemnants/wremnants/datasets/datagroups.py", line 89, in setHists
    group[label] = group["signalOp"](group[label])
  File "/home/t/tyjyang/analysis/wmass/WRemnants/wremnants/histselections.py", line 31, in signalHistWmass
    return h[sel]
  File "/opt/venv/lib/python3.10/site-packages/hist/basehist.py", line 318, in __getitem__
    return super().__getitem__(self._index_transform(index))
  File "/opt/venv/lib/python3.10/site-packages/hist/basehist.py", line 294, in _index_transform
    new_indices = {
  File "/opt/venv/lib/python3.10/site-packages/hist/basehist.py", line 296, in <dictcomp>
    self._name_to_index(k) if isinstance(k, str) else k
  File "/opt/venv/lib/python3.10/site-packages/hist/basehist.py", line 161, in _name_to_index
    raise ValueError(f"The axis name {name} could not be found")
ValueError: The axis name passIso could not be found
```
@kdlong @bendavid @cippy

**Comment by tyjyang** [comment]
Hi @cippy, thanks for the comments. Do you know which flags I should use for the top luminosity and efficiency histograms from the W histmaker?

**Comment by cippy** [comment]
Sorry for the late reply.
They should work without the need of any specific option. 

The luminosity one is just a lnN for the W-like analysis, while it becomes a shape variation for Wmass because it is propagated to fakes.

For the efficiency there isolation component is by default decorrelated between charges, which requires a scaling of sqrt(2) to account for the fact that isolation efficiencies were measured inclusively in charge.
One can correlate those using option --correlateEffStatIsoByCharge . 
I actually think we should change this part, I verified that isolation efficiencies do not depend on charge, so I think there is no point in forcing them to be decorrelated, it only increases the total uncertainty.

**Comment by tyjyang** [comment]
The fit now runs for me, with the following parts of the card excluded:
- luminosity
- muonL1PrefireSyst
- muonL1PrefireStat
- ecalL1Prefire
- `--noEfficiencyUnc`
For the first 4 systematics, the downUpVar axis is not found in each case.
FOr the Efficiency, axis `reco-tracking-idiptrig-iso` in not found.

**Comment by tyjyang** [comment]
It turns out the culprit was a conditional with wrong indentation level [here](https://github.com/WMass/WRemnants/pull/87/files#diff-d4a110c5575451b61b90d23bb532ed889f3d41f6e1784d7a2bafe8c1f950d4e5R228).
